PrismAdminAPI/Models/Standard.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PrismAdminAPI.Models
{
    public class Standard
    {
        public long StandardId { get; set; }

        [DisplayName("Standard Name")]
        [Required(ErrorMessage ="Standard Name is required")]
        [Range(1, 15, ErrorMessage = "Please enter valid integer Number")]
        public string StandardName { get; set; }

        public string Description { get; set; }
        public bool IsActive { get; set; }
        public long CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public long ModifiedBy { get; set; }
        public DateTime ModifiedDate { get; set; }
    }
}

PrismAdminAPI/Controllers/StandardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PrismAdminAPI.Manager;
using PrismAdminAPI.Models;

namespace PrismAdminAPI.Controllers
{
    public class StandardController : Controller
    {
        private readonly IStandardManager standardManager;
        public StandardController(IStandardManager _standardManager)
        {
            standardManager = _standardManager;
        }
        
        /// <summary>
        /// get all standard list 
        /// </summary>
        /// <returns></returns>
        [Route("standardlist")]
        [Route("Standard/ListStandard")]
        public ActionResult ListStandard()
        {
            IEnumerable<Standard> _standardList = standardManager.GetStandardList();
            return View(_standardList);
        }

        /// <summary>
        /// Add Standard
        /// </summary>
        /// <returns></returns>
        [Route("addstandard")]
        [Route("Standard/AddStandard")]
        public ActionResult AddStandard()
        {
            return View();
        }

        /// <summary>
        /// Insert standard 
        /// </summary>
        /// <param name="_standard"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult InsertStandard(Standard _standard)
        {
            long _insertResult = standardManager.InsertStandard(_standard);
            return RedirectToAction("ListStandard");
        }

        /// <summary>
        /// Update Standard
        /// </summary>
        /// <returns></returns>
        [Route("editstandard/{standardId}")]
        [Route("Standard/EditStandard/{standardId}")]
        public ActionResult EditStandard(int standardId)
        {
            Standard _standard = standardManager.GetStandardList(standardId).FirstOrDefault();
            if(_standard==null)
            {
                return View("ListStandard");
            }
            return View(_standard);
        }

        /// <summary>
        /// Update standard 
        /// </summary>
        /// <param name="_standard"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UpdateStandard(Standard _standard)
        {
            long _updateResult = standardManager.UpdateStandard(_standard);
            return RedirectToAction("ListStandard");
        }

        /// <summary>
        /// Activate or Deactivate the standard
        /// </summary>
        /// <param name="_standard"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult ActiveDeactiveStandard(Standard _standard)
        {
            long _activateDeactivateResult = standardManager.ActivateDeactivateStandard(_standard.StandardId,_standard.IsActive);
            return Json(_activateDeactivateResult);
        }
    }
}

PrismAdminAPI/Views/Standard/AddStandard.cshtml
@model PrismAdminAPI.Models.Standard
@{
    ViewBag.Title = "Add Standard";
}
<link rel="stylesheet" href="../../ThemeContent/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
<div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Standard</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Add Standanrd</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <!-- /.card -->
                    <div class="card">
                        <div class="card-header">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h3 class="card-title">Add Standard</h3>
                                </div>
                                <div class="col-sm-6">
                                    <a href="/standardlist" class="btn btn-danger float-right">Standard List</a>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            @using (Html.BeginForm("InsertStandard", "Standard"))
                            {
                                @Html.ValidationSummary(true);
                                <div class="card-body">
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.StandardName)
                                        @Html.TextBoxFor(m=>m.StandardName,new { @class= "form-control" })
                                        @Html.ValidationMessageFor(m => m.StandardName,null,new { @class="danger" })
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.Description)
                                        @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Description, null, new { @class = "danger" })
                                    </div>
                                </div>
                                <!-- /.card-body -->
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            }
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
   
</div>

PrismAdminAPI/Views/Standard/EditStandard.cshtml
@model PrismAdminAPI.Models.Standard
@{
    ViewBag.Title = "Update Standard";
}
<link rel="stylesheet" href="../../ThemeContent/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
<div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Standard</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Update Standanrd</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <!-- /.card -->
                    <div class="card">
                        <div class="card-header">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h3 class="card-title">Update Standard</h3>
                                </div>
                                <div class="col-sm-6">
                                    <a href="/standardlist" class="btn btn-danger float-right">Standard List</a>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            @using (Html.BeginForm("UpdateStandard", "Standard"))
                            {
                                @Html.ValidationSummary(true);
                                @Html.HiddenFor(m=>m.IsActive)
                                @Html.HiddenFor(m=>m.StandardId)
                                <div class="card-body">
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.StandardName)
                                        @Html.TextBoxFor(m => m.StandardName, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.StandardName, null, new { @class = "danger" })
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.Description)
                                        @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Description, null, new { @class = "danger" })
                                    </div>
                                </div>
                                <!-- /.card-body -->
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            }
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>

</div>

PrismAdminAPI/Views/Standard/ListStandard.cshtml
@model IEnumerable<PrismAdminAPI.Models.Standard>
@{
    ViewBag.Title = "List Standard";
}
<link rel="stylesheet" href="../../ThemeContent/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
<div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Standard</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Standanrd List</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="row h-100 d-none" id="divAlertMessage">
                <div class="col-sm-12 alert alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h5><i class="icon fas fa-ban"></i> Alert!</h5>
                    <span class="textMessage"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <!-- /.card -->
                    <div class="card">
                        <div class="card-header">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h3 class="card-title">Standard List</h3>
                                </div>
                                <div class="col-sm-6">
                                    <a href="/addstandard" class="btn btn-primary float-right">Add Standard</a>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="tblStandard" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>Standard Id</th>
                                        <th>Standard Name</th>
                                        <th>Description</th>
                                        <th>Active/Deactive</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.StandardId</td>
                                            <td>@item.StandardName</td>
                                            <td>@item.Description</td>
                                            <td>
                                                @{
                                                    string _isActive = item.IsActive == true ? "checked" : "";
                                                }
                                                <div class="custom-control custom-checkbox">
                                                    <input class="custom-control-input" data-serialid="@item.StandardId" onclick="ActiveDeactive(this)" type="checkbox" id="chkStandard-@item.StandardId" @_isActive>
                                                    <label for="chkStandard-@item.StandardId" class="custom-control-label"></label>
                                                </div>
                                            </td>
                                            <td>
                                                <button class="btn btn-link" onclick="javascript: location.href= 'editstandard/@item.StandardId'" >Edit</button>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>Standard Id</th>
                                        <th>Standard Name</th>
                                        <th>Description</th>
                                        <th>Active/Deactive</th>
                                        <th>Action</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
    <script src="../../ThemeContent/plugins/datatables/jquery.dataTables.js"></script>
    <script src="../../ThemeContent/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <script src="~/ThemeScript/Standard.js"></script>
    <script>
        
        var _urlActiveDeactiveStandard = '@Url.Action("ActiveDeactiveStandard", "Standard")';
        $(function () {
            $('#tblStandard').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
            });
        });

        
    </script>
</div>