PrismAdminAPI/Models/StandardMedium.cs
using System;

namespace PrismAdminAPI.Models
{
    public class StandardMedium
    {
        public long StandardMediumId { get; set; }

        public long StandardId { get; set; }
        public string StandardName { get; set; }
        public string StandardDescription { get; set; }

        public long MediumId { get; set; }
        public string MediumName { get; set; }
        public string MediumDescription { get; set; }

        public bool IsActive { get; set; }

        public long CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public long ModifiedBy { get; set; }
        public DateTime ModifiedDate { get; set; }
    }
}

PrismAdminAPI/Controllers/ConfigurationController.cs
using PrismAdminAPI.Manager;
using PrismAdminAPI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PrismAdminAPI.Controllers
{
    public class ConfigurationController : Controller
    {
        private IConfigurationManager configurationManager;
        public ConfigurationController(IConfigurationManager _configurationManager)
        {
            configurationManager = _configurationManager;
        }

        // GET: Configuration
        [Route("standardmedium")]
        [Route("Configuration/StandardMedium")]
        public ActionResult StandardMedium()
        {
            var _standardMedium = configurationManager.GetStandardMediamConfiguration();
            return View(_standardMedium);
        }
        /// <summary>
        /// Activate or Deactivate the standard/Medium
        /// </summary>
        /// <param name="_standard"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult ActiveDeactiveStandardMedium(StandardMedium _standardMedium)
        {
            long _activateDeactivateResult = configurationManager.InsertStandardMedium(_standardMedium);
            return Json(_activateDeactivateResult);
        }

    }
}

PrismAdminAPI/Views/Configuration/StandardMedium.cshtml
@model IEnumerable<PrismAdminAPI.Models.StandardMedium>
@{
    ViewBag.Title = "List Standard";
}
@{
    var _standardList = Model.Select(x => new { x.StandardId, x.StandardName, x.StandardDescription }).Distinct();
    var _mediumList = Model.Select(x => new { x.MediumId, x.MediumName, x.MediumDescription }).Distinct();
}
<link rel="stylesheet" href="../../ThemeContent/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
<div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Standard Medium Configuration</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Standard Medium Configuration</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="row h-100 d-none" id="divAlertMessage">
                <div class="col-sm-12 alert alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h5><i class="icon fas fa-ban"></i> Alert!</h5>
                    <span class="textMessage"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <!-- /.card -->
                    <div class="card">
                        <div class="card-header">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h3 class="card-title">Standard Medium Configuration</h3>
                                </div>
                                <div class="col-sm-6">
                                    &nbsp;
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="tblStandardMediumConfiguration" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>Standard Id</th>
                                        <th>Standard Name</th>
                                        <th>Description</th>
                                        <th>Active/Deactive Mediums</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var standard in _standardList)
                                    {
                                        <tr>
                                            <td>@standard.StandardId</td>
                                            <td>@standard.StandardName</td>
                                            <td>@standard.StandardDescription</td>
                                            <td>
                                                @foreach (var medium in _mediumList)
                                                {
                                                    string standardMedium = String.Format("chkStandardMedium-{0}-{1}", standard.StandardId, medium.MediumId);
                                                    var standardModelDetails = Model.Where(x => x.StandardId == standard.StandardId && x.MediumId == medium.MediumId).FirstOrDefault();
                                                    string isChecked = (standardModelDetails != null && Convert.ToInt32(standardModelDetails.StandardMediumId) != 0 && standardModelDetails.IsActive == true) ? "checked" : "";
                                                    <div class="custom-control custom-checkbox">
                                                        <input class="custom-control-input" data-standardId="@standard.StandardId" data-mediumId="@medium.MediumId" onclick="ActiveDeactive(this)" type="checkbox" id="@standardMedium" @isChecked>
                                                        <label for="@standardMedium" class="custom-control-label">@medium.MediumName</label>
                                                    </div>
                                                }

                                            </td>
                                        </tr>
                                    }
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>Standard Id</th>
                                        <th>Standard Name</th>
                                        <th>Description</th>
                                        <th>Active/Deactive</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
    <script src="../../ThemeContent/plugins/datatables/jquery.dataTables.js"></script>
    <script src="../../ThemeContent/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <script src="~/ThemeScript/StandardMedium.js"></script>
    <script>

        var _urlActiveDeactiveStandardMedium = '@Url.Action("ActiveDeactiveStandardMedium", "Configuration")';
        $(function () {
            $('#tblStandardMediumConfiguration').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
            });
        });


    </script>
</div>