PrismAdminAPI/Models/Medium.cs
using System;

namespace PrismAdminAPI.Models
{
    public class Medium
    {
        public int MediumId { get; set; }
        public string MediumName { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public long CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public long ModifiedBy { get; set; }
        public DateTime ModifiedDate { get; set; }
    }
}

PrismAdminAPI/Controllers/MediumController.cs
using PrismAdminAPI.Manager;
using PrismAdminAPI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PrismAdminAPI.Controllers
{
    public class MediumController : Controller
    {
        private readonly IMediumManager mediumManager;
        public MediumController(IMediumManager _mediumManager)
        {
            mediumManager = _mediumManager;
        }

        /// <summary>
        /// get all medium list 
        /// </summary>
        /// <returns></returns>
        [Route("mediumlist")]
        [Route("Medium/ListMedium")]
        public ActionResult ListMedium()
        {
            IEnumerable<Medium> _mediumList = mediumManager.GetMediumList();
            return View(_mediumList);
        }

        /// <summary>
        /// Add Medium
        /// </summary>
        /// <returns></returns>
        [Route("addmedium")]
        [Route("Medium/AddMedium")]
        public ActionResult AddMedium()
        {
            return View();
        }

        /// <summary>
        /// Insert Medium 
        /// </summary>
        /// <param name="_medium"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult InsertMedium(Medium _medium)
        {
            long _insertResult = mediumManager.InsertMedium(_medium);
            return RedirectToAction("ListMedium");
        }

        /// <summary>
        /// Update Standard
        /// </summary>
        /// <returns></returns>
        [Route("editmedium/{mediumId}")]
        [Route("Medium/EditMedium/{mediumId}")]
        public ActionResult EditMedium(int mediumId)
        {
            Medium _medium = mediumManager.GetMediumList(mediumId).FirstOrDefault();
            if (_medium == null)
            {
                return View("ListMedium");
            }
            return View(_medium);
        }

        /// <summary>
        /// Update medium 
        /// </summary>
        /// <param name="_medium"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UpdateMedium(Medium _medium)
        {
            long _updateResult = mediumManager.UpdateMedium(_medium);
            return RedirectToAction("ListMedium");
        }

        /// <summary>
        /// Activate or Deactivate the medium
        /// </summary>
        /// <param name="_medium"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult ActiveDeactiveMedium(Medium _medium)
        {
            long _activateDeactivateResult = mediumManager.ActivateDeactivateMedium(_medium.MediumId, _medium.IsActive);
            return Json(_activateDeactivateResult);
        }
    }
}

PrismAdminAPI/Views/Medium/AddMedium.cshtml
@model PrismAdminAPI.Models.Medium
@{
    ViewBag.Title = "Add Medium";
}
<link rel="stylesheet" href="../../ThemeContent/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
<div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Medium</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Add Medium</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <!-- /.card -->
                    <div class="card">
                        <div class="card-header">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h3 class="card-title">Add Medium</h3>
                                </div>
                                <div class="col-sm-6">
                                    <a href="/mediumlist" class="btn btn-danger float-right">Medium List</a>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            @using (Html.BeginForm("InsertMedium", "Medium"))
                            {
                                @Html.ValidationSummary(true);
                                <div class="card-body">
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.MediumName)
                                        @Html.TextBoxFor(m=>m.MediumName, new { @class= "form-control" })
                                        @Html.ValidationMessageFor(m => m.MediumName, null,new { @class="danger" })
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.Description)
                                        @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Description, null, new { @class = "danger" })
                                    </div>
                                </div>
                                <!-- /.card-body -->
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            }
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
   
</div>

PrismAdminAPI/Views/Medium/EditMedium.cshtml
@model PrismAdminAPI.Models.Medium
@{
    ViewBag.Title = "Update Medium";
}
<link rel="stylesheet" href="../../ThemeContent/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
<div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Medium</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Update Medium</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <!-- /.card -->
                    <div class="card">
                        <div class="card-header">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h3 class="card-title">Update Medium</h3>
                                </div>
                                <div class="col-sm-6">
                                    <a href="/standardlist" class="btn btn-danger float-right">Medium List</a>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            @using (Html.BeginForm("UpdateMedium", "Medium"))
                            {
                                @Html.ValidationSummary(true);
                                @Html.HiddenFor(m=>m.IsActive)
                                @Html.HiddenFor(m=>m.MediumId)
                                <div class="card-body">
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.MediumName)
                                        @Html.TextBoxFor(m => m.MediumName, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.MediumName, null, new { @class = "danger" })
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(m => m.Description)
                                        @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Description, null, new { @class = "danger" })
                                    </div>
                                </div>
                                <!-- /.card-body -->
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            }
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>

</div>

PrismAdminAPI/Views/Medium/ListMedium.cshtml
@model IEnumerable<PrismAdminAPI.Models.Medium>
@{
    ViewBag.Title = "List Medium";
}
<link rel="stylesheet" href="../../ThemeContent/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
<div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Medium</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Medium List</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="row h-100 d-none" id="divAlertMessage">
                <div class="col-sm-12 alert alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h5><i class="icon fas fa-ban"></i> Alert!</h5>
                    <span class="textMessage"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <!-- /.card -->
                    <div class="card">
                        <div class="card-header">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h3 class="card-title">Medium List</h3>
                                </div>
                                <div class="col-sm-6">
                                    <a href="/addmedium" class="btn btn-primary float-right">Add Medium</a>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="tblMedium" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>Medium Id</th>
                                        <th>Medium Name</th>
                                        <th>Description</th>
                                        <th>Active/Deactive</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.MediumId</td>
                                            <td>@item.MediumName</td>
                                            <td>@item.Description</td>
                                            <td>
                                                @{
                                                    string _isActive = item.IsActive == true ? "checked" : "";
                                                }
                                                <div class="custom-control custom-checkbox">
                                                    <input class="custom-control-input" data-SerialId="@item.MediumId" onchange="ActiveDeactive(this)" type="checkbox" id="chkMedium-@item.MediumId" @_isActive>
                                                    <label for="chkMedium-@item.MediumId" class="custom-control-label"></label>
                                                </div>
                                            </td>
                                            <td>
                                                <button class="btn btn-link" onclick="javascript: location.href= 'editmedium/@item.MediumId'" >Edit</button>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>Medium Id</th>
                                        <th>Medium Name</th>
                                        <th>Description</th>
                                        <th>Active/Deactive</th>
                                        <th>Action</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
    <script src="../../ThemeContent/plugins/datatables/jquery.dataTables.js"></script>
    <script src="../../ThemeContent/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <script src="~/ThemeScript/Medium.js"></script>
    <script>
        
        var _urlActiveDeactiveMedium = '@Url.Action("ActiveDeactiveMedium", "Medium")';
        $(function () {
            $('#tblMedium').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
            });
        });

        
    </script>
</div>