PrismAdminAPI/Models/Subject.cs
using PrismAdminAPI.ViewModel;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;

namespace PrismAdminAPI.Models
{
    public class Subject
    {
        public long SubjectId { get; set; }

        [DisplayName("Subject Name")]
        [Required(ErrorMessage = "Subject Name is required")]
        public string SubjectName { get; set; }

        [Required(ErrorMessage = "Please select standard")]
        public long StandardId { get; set; }

        public long MediumId { get; set; }

        [DisplayName("Configured Mediums")]
        [Required(ErrorMessage = "Please select medium")]
        public string MediumIdList { get; set; }

        [DisplayName("Thumbnail Image")]
        public HttpPostedFileBase SubjectThumbnail { get; set; }

        public string Description { get; set; }
        
        public IEnumerable<SelectListItem> StandardList { get; set; }

        public bool IsActive { get; set; }
        public long CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public long ModifiedBy { get; set; }
        public DateTime ModifiedDate { get; set; }

        public SubjectViewModel SubjectViewModel { get; set; }
    }
}

PrismAdminAPI/Controllers/SubjectController.cs
using PrismAdminAPI.Manager;
using PrismAdminAPI.Models;
using PrismAdminAPI.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PrismAdminAPI.Controllers
{
    public class SubjectController : Controller
    {
        private readonly IStandardManager standardManager;
        private readonly IMediumManager mediumManager;
        private readonly IConfigurationManager configurationManager;
        private readonly ISubjectManager subjectManager;
        public SubjectController(IStandardManager _standardManager, 
            IMediumManager _mediumManager, 
            IConfigurationManager _configurationManager,
            ISubjectManager _subjectManager)
        {
            standardManager = _standardManager;
            mediumManager = _mediumManager;
            configurationManager = _configurationManager;
            subjectManager = _subjectManager;
        }

        [Route("subjectadd")]
        [Route("Subject/AddSubject")]
        public ActionResult AddSubject()
        {
            Subject _subject = new Subject();
            _subject = GetSubjectObjectDetails();
            return View(_subject);
        }

        [HttpPost]
        public ActionResult InsertSubject(Subject _subject)
        {
            long addResult = subjectManager.InsertSubject(_subject);
            return RedirectToAction("Subject/AddSubject");
        }


        [HttpGet]
        public JsonResult GetMediumsBySubjectId(long _standardId)
        {
            return Json(configurationManager.GetConfiguredStandardMediamConfiguration(_standardId),JsonRequestBehavior.AllowGet);
        }

        [NonAction]
        public Subject GetSubjectObjectDetails(IEnumerable<SubjectViewModel> _subjectViewModelList=null)
        {
            Subject _subject = new Subject();
            if (_subjectViewModelList!=null)
            {
                SubjectViewModel subjectViewModel = _subjectViewModelList.FirstOrDefault();
                _subject.SubjectId = subjectViewModel.SubjectId;
                _subject.SubjectName = subjectViewModel.SubjectName;
                _subject.Description = subjectViewModel.Description;
                _subject.StandardId = subjectViewModel.StandardId;
                _subject.MediumIdList = string.Join(",", _subjectViewModelList.Where(x=>x.IsSubjectMediumActive==true).Select(x => x.MediumId));
                _subject.SubjectViewModel = subjectViewModel;
            }
            _subject.StandardList = standardManager.GetStandardList(null, true).Select(x => new SelectListItem { Text = String.Format("{0} ({1})", x.StandardName, x.Description), Value = x.StandardId.ToString() });
            return _subject;
        }

        [Route("subjectlist")]
        [Route("Subject/ListSubject")]
        public ActionResult ListSubject()
        {
            var subjectList = subjectManager.GetSubjectList();
            return View(subjectList);
        }

        [HttpPost]
        public JsonResult ActiveDeactiveSubject(Subject _subject)
        {
            long _activateDeactivateResult = subjectManager.ActivateDeactivateSubject(_subject.SubjectId, _subject.IsActive);
            return Json(_activateDeactivateResult);
        }

        [Route("editsubject/{subjectId}")]
        [Route("Subject/EditSubject/{subjectId}")]
        public ActionResult EditSubject(long subjectId)
        {
            IEnumerable<SubjectViewModel> _subjectViewModelList = subjectManager.GetSubjectList(subjectId);
            
            Subject _subject = new Subject();
            if (_subjectViewModelList.Count() == 0)
            {
                return View("ListStandard");
            }
            else
            {
                _subject = GetSubjectObjectDetails(_subjectViewModelList);
            }
            return View(_subject);
        }

        [HttpPost]
        public ActionResult UpdateSubject(Subject _subject)
        {
            long updateResult = subjectManager.UpdateSubject(_subject);
            return RedirectToAction("ListSubject");
        }
    }
}

PrismAdminAPI/Views/Subject/AddSubject.cshtml
@model PrismAdminAPI.Models.Subject
@{
    ViewBag.Title = "Add Subject";
}
<link rel="stylesheet" href="../../ThemeContent/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
<div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Subject</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Add Subject</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <!-- /.card -->
                    <div class="card">
                        <div class="card-header">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h3 class="card-title">Add Subject</h3>
                                </div>
                                <div class="col-sm-6">
                                    <a href="/subjectlist" class="btn btn-danger float-right">Subject List</a>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="form-horizontal">


                            <div class="card-body">
                                @using (Html.BeginForm("InsertSubject", "Subject", FormMethod.Post, new { enctype = "multipart/form-data", role = "form" }))
                                {
                                    @Html.ValidationSummary(true);
                                    <div class="card-body">
                                        <div class="form-group row">
                                            @Html.LabelFor(m => m.SubjectName, new { @class = "col-sm-2 col-form-label" })
                                            <div class="col-sm-10">
                                                @Html.TextBoxFor(m => m.SubjectName, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(m => m.SubjectName, null, new { @class = "danger" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            @Html.LabelFor(m => m.StandardId, new { @class = "col-sm-2 col-form-label" })
                                            <div class="col-sm-10">
                                                @Html.DropDownListFor(m => m.StandardId, Model.StandardList, "-- Select Standard --", new { @class = "form-control ddlStandard" })
                                                @Html.ValidationMessageFor(m => m.StandardId, null, new { @class = "danger" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            @Html.LabelFor(m => m.MediumIdList, new { @class = "col-sm-2 col-form-label" })
                                            @Html.HiddenFor(m => m.MediumIdList)
                                            <div class="col-sm-10 div-configured-mediums">
                                                Configured Medium List (Please select standard)
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            @Html.LabelFor(m => m.Description, new { @class = "col-sm-2 col-form-label" })
                                            <div class="col-sm-10">
                                                @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(m => m.Description, null, new { @class = "danger" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            @Html.LabelFor(m => m.SubjectThumbnail, new { @class = "col-sm-2 col-form-label" })
                                            <div class="col-sm-5">
                                                <div class="custom-file">
                                                    @Html.TextBoxFor(m => m.SubjectThumbnail, new { type = "file", @class = "custom-file-input", accept = "image/*", onchange = "loadFile(event)" })
                                                    <label class="custom-file-label" for="customFile">Choose file</label>
                                                </div>
                                            </div>
                                            <div class="col-sm-5">
                                                <img id="imgSubjectUploadedFile" src="@WebConfig.DefaultImage" width="100" height="100" />
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                }
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>

</div>
<script src="~/ThemeContent/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
<script src="~/ThemeScript/Subject.js"></script>

<script>
    var _urlGetMediumsBySubjectId = '@Url.Action("GetMediumsBySubjectId", "Subject")';

    var loadFile = function (event) {
        var image = document.getElementById('imgSubjectUploadedFile');
        image.src = "";
        image.src = URL.createObjectURL(event.target.files[0]);
        image.clientHeight = 200;
        image.clientWidth = 200;
    };
</script>

PrismAdminAPI/Views/Subject/EditSubject.cshtml
@model PrismAdminAPI.Models.Subject
@{
    ViewBag.Title = "Edit Subject";
}
<link rel="stylesheet" href="../../ThemeContent/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
<div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Subject</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Edit Subject</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <!-- /.card -->
                    <div class="card">
                        <div class="card-header">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h3 class="card-title">Edit Subject</h3>
                                </div>
                                <div class="col-sm-6">
                                    <a href="/subjectlist" class="btn btn-danger float-right">Subject List</a>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="form-horizontal">


                            <div class="card-body">
                                @using (Html.BeginForm("UpdateSubject", "Subject", FormMethod.Post, new { enctype = "multipart/form-data", role = "form" }))
                                {
                                    @Html.ValidationSummary(true);
                                    @Html.HiddenFor(m => m.SubjectId)
                                    @Html.HiddenFor(m => m.MediumIdList)
                                    <div class="card-body">
                                        <div class="form-group row">
                                            @Html.LabelFor(m => m.SubjectName, new { @class = "col-sm-2 col-form-label" })
                                            <div class="col-sm-10">
                                                @Html.TextBoxFor(m => m.SubjectName, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(m => m.SubjectName, null, new { @class = "danger" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            @Html.LabelFor(m => m.StandardId, new { @class = "col-sm-2 col-form-label" })
                                            <div class="col-sm-10">
                                                @Html.DropDownListFor(m => m.StandardId, Model.StandardList, "-- Select Standard --", new { @class = "form-control ddlStandard" })
                                                @Html.ValidationMessageFor(m => m.StandardId, null, new { @class = "danger" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            @Html.LabelFor(m => m.MediumIdList, new { @class = "col-sm-2 col-form-label" })
                                            @Html.HiddenFor(m => m.MediumIdList)
                                            <div class="col-sm-10 div-configured-mediums">
                                                Configured Medium List (Please select standard)
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            @Html.LabelFor(m => m.Description, new { @class = "col-sm-2 col-form-label" })
                                            <div class="col-sm-10">
                                                @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(m => m.Description, null, new { @class = "danger" })
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            @Html.LabelFor(m => m.SubjectThumbnail, new { @class = "col-sm-2 col-form-label" })
                                            <div class="col-sm-5">
                                                <div class="custom-file">
                                                    @Html.TextBoxFor(m => m.SubjectThumbnail, new { type = "file", @class = "custom-file-input", accept = "image/*", onchange = "loadFile(event)" })
                                                    <label class="custom-file-label" for="customFile">Choose file</label>
                                                </div>
                                            </div>
                                            <div class="col-sm-5">
                                                @if (Model.SubjectViewModel.SubjectThumbnail == null)
                                                {
                                                    <img id="imgSubjectUploadedFile" src="~/ThemeImages/eballogo.gif" width="100" height="100" />
                                                }
                                                else
                                                {
                                                    var base64 = Convert.ToBase64String(Model.SubjectViewModel.SubjectThumbnail);
                                                    var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                                                    <img id="imgSubjectUploadedFile" src='@imgsrc' width="100" height="100" />
                                                }
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /.card-body -->
                                    <div class="card-footer">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                }
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>

</div>
<script src="~/ThemeContent/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
<script src="~/ThemeScript/Subject.js"></script>

<script>
    var _urlGetMediumsBySubjectId = '@Url.Action("GetMediumsBySubjectId", "Subject")';

    var loadFile = function (event) {
        var image = document.getElementById('imgSubjectUploadedFile');
        image.src = "";
        image.src = URL.createObjectURL(event.target.files[0]);
        image.clientHeight = 200;
        image.clientWidth = 200;
    };
</script>

PrismAdminAPI/Views/Subject/ListSubject.cshtml
@model IEnumerable<PrismAdminAPI.ViewModel.SubjectViewModel>
@{
    ViewBag.Title = "Subject List";
}

@{
    var _subjectIdList = Model.Select(x => new {x.SubjectId}).Distinct();
}
<link rel="stylesheet" href="../../ThemeContent/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
<div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Subject List</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Subject List</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="row h-100 d-none" id="divAlertMessage">
                <div class="col-sm-12 alert alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h5><i class="icon fas fa-ban"></i> Alert!</h5>
                    <span class="textMessage"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <!-- /.card -->
                    <div class="card">
                        <div class="card-header">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h3 class="card-title">Subject List</h3>
                                </div>
                                <div class="col-sm-6">
                                    <a href="/subjectadd" class="btn btn-danger float-right">Add Subject</a>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="tblSubject" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>Subject Name</th>
                                        <th>Subject Icon</th>
                                        <th>Standard</th>
                                        <th>Mediums Configured</th>
                                        <th>Active/Deactive</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var subject in _subjectIdList)
                                    {
                                        var subjectDetails = Model.Where(x => x.SubjectId == subject.SubjectId)
                                            .Select(x =>
                                                new
                                                {
                                                    SubjectId = x.SubjectId,
                                                    SubjectName = x.SubjectName,
                                                    IsSubjectActive = x.IsSubjectActive,
                                                    StandardId = x.StandardId,
                                                    StandardName = x.StandardName,
                                                    SubjectThumbnail = x.SubjectThumbnail

                                                }
                                            ).FirstOrDefault();

                                        var mediumList = Model.Where(x => x.SubjectId == subject.SubjectId && x.IsSubjectMediumActive == true).Select(x =>
                                                  new
                                                  {
                                                      MediumId = x.MediumId,
                                                      MediumName = x.MediumName,
                                                      IsSubjectMediumActive = x.IsSubjectMediumActive
                                                  }
                                            ).ToList();

                                        <tr>
                                            <td>@subjectDetails.SubjectName</td>
                                            <td>
                                                @{
                                                    var base64 = Convert.ToBase64String(subjectDetails.SubjectThumbnail);
                                                    var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                                                }
                                                <img src='@imgsrc' style="max-width:100px;max-height:100px" />
                                            </td>
                                            <td>@subjectDetails.StandardName</td>
                                            <td>
                                                @foreach (var medium in mediumList)
                                                {
                                                    <label>@medium.MediumName</label>
                                                    <br />
                                                }
                                            </td>
                                            <td>
                                                @{
                                                    string _isActive = subjectDetails.IsSubjectActive == true ? "checked" : "";
                                                }
                                                <div class="custom-control custom-checkbox">
                                                    <input class="custom-control-input" data-serialid="@subjectDetails.SubjectId" onclick="ActiveDeactive(this)" type="checkbox" id="chkSubject-@subjectDetails.SubjectId" @_isActive>
                                                    <label for="chkSubject-@subjectDetails.SubjectId" class="custom-control-label"></label>
                                                </div>
                                            </td>
                                            <td>
                                                <button class="btn btn-link" onclick="javascript: location.href= 'editsubject/@subjectDetails.SubjectId'">Edit</button>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>Subject Name</th>
                                        <th>Subject Icon</th>
                                        <th>Standard</th>
                                        <th>Mediums Configured</th>
                                        <th>Active/Deactive</th>
                                        <th>Action</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
    <script src="../../ThemeContent/plugins/datatables/jquery.dataTables.js"></script>
    <script src="../../ThemeContent/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <script src="~/ThemeScript/Subject.js"></script>
    <script>
        var _urlActiveDeactiveSubject='@Url.Action("ActiveDeactiveSubject", "Subject")'
        $(function () {
            $('#tblSubject').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
            });
        });
    </script>
</div>